(define (tokenize lst sep acc)
  (if (null? lst)
      (if (null? acc)
          '()
          (cons (list->string (reverse acc)) '()))
      (if (eq? sep (car lst))
          (cons (list->string (reverse acc)) (tokenize (cdr lst) sep '()))
          (tokenize (cdr lst) sep (cons (car lst) acc)))))

(for-each print (tokenize (string->list "Hello,How,Are,You,Today") #\, '()))
