(define (sum-t t)
  (if (number? t)
      t
      (+ (sum-t (car t)) (sum-t (cdr t)))))
(define (pud t)
  (cons (cons (car t)
              (cdr t))
        (car t)))
(define (fib-t n)
  (if (< n 2)
      '(1 . 1)
      (pud (fib-t (- n 1)))))
(define (fib n) (sum-t (fib-t n)))
(fib 1)
(fib 2)
(fib 3)
(fib 4)
(fib 5)
(fib 6)
(fib 7)
(fib 8)
(fib 9)
(fib 10)
(fib 11)
(fib 12)
(fib 13)
