(define (mk-list e n) (if (= n 0) '() (cons e (mk-list e (- n 1)))))
(define (go)
 (mk-list 'a 30)
 (mk-list 'b 60)
 (mk-list 'c 90)
 (mk-list 'x 30)
 (mk-list 'y 60)
 (mk-list 'z 90)
 (mk-list (mk-list '(u f o) 3) 5)
 (mk-list (mk-list '(u f o) 10) 20)
 (mk-list (mk-list '(u f o) 30) 40))
(go) (go) (go) (go)
